In [1]:
import numpy as np

In [3]:
arr1=np.arange(1,17).reshape(4,4)
print(arr1)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [4]:
arr2=np.arange(1,17).reshape(4,4)
print(arr2)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [5]:
list1=[1,2,3,4]
list2=[2,3,4,5]

In [6]:
list1+list2

[1, 2, 3, 4, 2, 3, 4, 5]

In [7]:
arr1+arr2

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16],
       [18, 20, 22, 24],
       [26, 28, 30, 32]])

In [9]:
np.concatenate((arr1,arr2))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [10]:
print(arr1)
print(arr2)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [11]:
np.concatenate((arr1,arr2),axis=0)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [12]:
np.concatenate((arr1,arr2),axis=1)

array([[ 1,  2,  3,  4,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  5,  6,  7,  8],
       [ 9, 10, 11, 12,  9, 10, 11, 12],
       [13, 14, 15, 16, 13, 14, 15, 16]])

In [13]:
np.vstack((arr1,arr2))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [15]:
np.hstack((arr1,arr2))

array([[ 1,  2,  3,  4,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  5,  6,  7,  8],
       [ 9, 10, 11, 12,  9, 10, 11, 12],
       [13, 14, 15, 16, 13, 14, 15, 16]])

In [16]:
np.concatenate((arr1,arr2,arr1))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [17]:
ws=np.concatenate((arr1,arr2,arr1),axis=1)
print(ws)

[[ 1  2  3  4  1  2  3  4  1  2  3  4]
 [ 5  6  7  8  5  6  7  8  5  6  7  8]
 [ 9 10 11 12  9 10 11 12  9 10 11 12]
 [13 14 15 16 13 14 15 16 13 14 15 16]]


In [19]:
w1=np.hstack((arr1,arr2,arr1))
print(w1)

[[ 1  2  3  4  1  2  3  4  1  2  3  4]
 [ 5  6  7  8  5  6  7  8  5  6  7  8]
 [ 9 10 11 12  9 10 11 12  9 10 11 12]
 [13 14 15 16 13 14 15 16 13 14 15 16]]


In [21]:
w2=np.split(arr1,2)
print(w2)

[array([[1, 2, 3, 4],
       [5, 6, 7, 8]]), array([[ 9, 10, 11, 12],
       [13, 14, 15, 16]])]


In [22]:
type(w2)

list

In [23]:
w2[0]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [24]:
w2[1]

array([[ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [26]:
type(w2[0])

numpy.ndarray

In [31]:
arr1=np.array([1,2,3,4,5])

In [32]:
np.split(arr1,[1,2,3])

[array([1]), array([2]), array([3]), array([4, 5])]

In [33]:
np.split(arr1,[1,3])

[array([1]), array([2, 3]), array([4, 5])]

In [34]:
np.split(arr1,[1,4])

[array([1]), array([2, 3, 4]), array([5])]

In [35]:
np.split(arr1,[0,4])

[array([], dtype=int32), array([1, 2, 3, 4]), array([5])]

In [ ]:
print(arr1)